#!/bin/bash
#SBATCH -J RewardModel                               # 作业名为 test
#SBATCH -o RM-%j.out                        # 屏幕上的输出文件重定向到 test.out
#SBATCH -p compute                            # 作业提交的分区为 compute
#SBATCH -N 1                                  # 作业申请 1 个节点
#SBATCH -t 12:00:00                           # 任务运行的最长时间为 1 小时
#SBATCH --mem 192g
#SBATCH -w gpu09
#SBATCH --gres=gpu:a100-sxm4-80gb:6

# source ~/.bashrc

# 设置运行环境

# 输入要执行的命令，例如 ./hello 或 python test.py 等
./scripts/run_xverse_7b.sh                    # 执行命令(base)
